<?php

return [
    [
        'istat' => '25001',
        'nome'  => 'Agordo',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25002',
        'nome'  => 'Alano di Piave',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25003',
        'nome'  => 'Alleghe',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25072',
        'nome'  => 'Alpago',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25004',
        'nome'  => "Arsie'",
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25005',
        'nome'  => 'Auronzo di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25006',
        'nome'  => 'Belluno',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25007',
        'nome'  => 'Borca di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25074',
        'nome'  => 'Borgo Valbelluna',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25008',
        'nome'  => 'Calalzo di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25023',
        'nome'  => "Canale d'Agordo",
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25010',
        'nome'  => 'Cencenighe Agordino',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25011',
        'nome'  => 'Cesiomaggiore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25012',
        'nome'  => "Chies d'Alpago",
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25013',
        'nome'  => 'Cibiana di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25014',
        'nome'  => 'Colle Santa Lucia',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25015',
        'nome'  => 'Comelico Superiore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25016',
        'nome'  => "Cortina d'Ampezzo",
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25017',
        'nome'  => 'Danta di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25018',
        'nome'  => 'Domegge di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25019',
        'nome'  => 'Falcade',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25021',
        'nome'  => 'Feltre',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25022',
        'nome'  => 'Fonzaso',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25025',
        'nome'  => 'Gosaldo',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25027',
        'nome'  => 'La Valle Agordina',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25026',
        'nome'  => 'Lamon',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25029',
        'nome'  => 'Limana',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25030',
        'nome'  => 'Livinallongo del Col di Lana',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25071',
        'nome'  => 'Longarone',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25032',
        'nome'  => 'Lorenzago di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25033',
        'nome'  => 'Lozzo di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25035',
        'nome'  => 'Ospitale di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25036',
        'nome'  => 'Pedavena',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25037',
        'nome'  => 'Perarolo di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25039',
        'nome'  => 'Pieve di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25040',
        'nome'  => 'Ponte nelle Alpi',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25070',
        'nome'  => 'Quero Vas',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25043',
        'nome'  => 'Rivamonte Agordino',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25044',
        'nome'  => 'Rocca Pietore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25045',
        'nome'  => 'San Gregorio nelle Alpi',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25046',
        'nome'  => "San Nicolo' di Comelico",
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25047',
        'nome'  => 'San Pietro di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25049',
        'nome'  => 'San Tomaso Agordino',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25051',
        'nome'  => 'San Vito di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25048',
        'nome'  => 'Santa Giustina',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25050',
        'nome'  => 'Santo Stefano di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25053',
        'nome'  => 'Sedico',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25054',
        'nome'  => 'Selva di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25055',
        'nome'  => 'Seren del Grappa',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25056',
        'nome'  => 'Sospirolo',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25057',
        'nome'  => 'Soverzene',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25058',
        'nome'  => 'Sovramonte',
        'provincia' => 'BL',
        'zona_bollettino' => 'Feltre',
        'frazioni' => [],
    ],
    [
        'istat' => '25059',
        'nome'  => 'Taibon Agordino',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25060',
        'nome'  => 'Tambre',
        'provincia' => 'BL',
        'zona_bollettino' => 'Belluno',
        'frazioni' => [],
    ],
    [
        'istat' => '25073',
        'nome'  => 'Val di Zoldo',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25062',
        'nome'  => 'Vallada Agordina',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25063',
        'nome'  => 'Valle di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25065',
        'nome'  => 'Vigo di Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25066',
        'nome'  => 'Vodo Cadore',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25067',
        'nome'  => 'Voltago Agordino',
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '25069',
        'nome'  => "Zoppe' di Cadore",
        'provincia' => 'BL',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
];
