<?php

return [
    [
        'istat' => '28001',
        'nome'  => 'Abano Terme',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28002',
        'nome'  => 'Agna',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28003',
        'nome'  => 'Albignasego',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28004',
        'nome'  => 'Anguillara Veneta',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28005',
        'nome'  => "Arqua' Petrarca",
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28006',
        'nome'  => 'Arre',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28007',
        'nome'  => 'Arzergrande',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28008',
        'nome'  => 'Bagnoli di Sopra',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28009',
        'nome'  => 'Baone',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28010',
        'nome'  => 'Barbona',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28011',
        'nome'  => 'Battaglia Terme',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28012',
        'nome'  => 'Boara Pisani',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28107',
        'nome'  => 'Borgo Veneto',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28013',
        'nome'  => 'Borgoricco',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28014',
        'nome'  => 'Bovolenta',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28015',
        'nome'  => 'Brugine',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28016',
        'nome'  => 'Cadoneghe',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28020',
        'nome'  => 'Campo San Martino',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28017',
        'nome'  => 'Campodarsego',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28018',
        'nome'  => 'Campodoro',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28019',
        'nome'  => 'Camposampiero',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28021',
        'nome'  => 'Candiana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28022',
        'nome'  => 'Carceri',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28023',
        'nome'  => 'Carmignano di Brenta',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28026',
        'nome'  => 'Cartura',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28027',
        'nome'  => 'Casale di Scodosia',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28028',
        'nome'  => 'Casalserugo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28029',
        'nome'  => 'Castelbaldo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28030',
        'nome'  => 'Cervarese Santa Croce',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28031',
        'nome'  => 'Cinto Euganeo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28032',
        'nome'  => 'Cittadella',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28033',
        'nome'  => 'Codevigo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28034',
        'nome'  => 'Conselve',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28035',
        'nome'  => 'Correzzola',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28036',
        'nome'  => 'Curtarolo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28106',
        'nome'  => 'Due Carrare',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28037',
        'nome'  => 'Este',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28038',
        'nome'  => 'Fontaniva',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28039',
        'nome'  => 'Galliera Veneta',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28040',
        'nome'  => 'Galzignano Terme',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28041',
        'nome'  => 'Gazzo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28042',
        'nome'  => 'Grantorto',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28043',
        'nome'  => 'Granze',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28044',
        'nome'  => 'Legnaro',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28045',
        'nome'  => 'Limena',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28046',
        'nome'  => 'Loreggia',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28047',
        'nome'  => 'Lozzo Atestino',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28048',
        'nome'  => "Masera' di Padova",
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28049',
        'nome'  => 'Masi',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28050',
        'nome'  => 'Massanzago',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28052',
        'nome'  => 'Megliadino San Vitale',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28053',
        'nome'  => 'Merlara',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28054',
        'nome'  => 'Mestrino',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28055',
        'nome'  => 'Monselice',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28056',
        'nome'  => 'Montagnana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28057',
        'nome'  => 'Montegrotto Terme',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28058',
        'nome'  => 'Noventa Padovana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28059',
        'nome'  => 'Ospedaletto Euganeo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28060',
        'nome'  => 'Padova',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28061',
        'nome'  => 'Pernumia',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28062',
        'nome'  => "Piacenza d'Adige",
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28063',
        'nome'  => 'Piazzola sul Brenta',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28064',
        'nome'  => 'Piombino Dese',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28065',
        'nome'  => 'Piove di Sacco',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28066',
        'nome'  => 'Polverara',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28067',
        'nome'  => 'Ponso',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28069',
        'nome'  => "Ponte San Nicolo'",
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28068',
        'nome'  => 'Pontelongo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28070',
        'nome'  => 'Pozzonovo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28071',
        'nome'  => 'Rovolon',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28072',
        'nome'  => 'Rubano',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28073',
        'nome'  => 'Saccolongo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28075',
        'nome'  => 'San Giorgio delle Pertiche',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28076',
        'nome'  => 'San Giorgio in Bosco',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28077',
        'nome'  => 'San Martino di Lupari',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28078',
        'nome'  => "San Pietro in Gu'",
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28079',
        'nome'  => 'San Pietro Viminario',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28080',
        'nome'  => 'Santa Giustina in Colle',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28082',
        'nome'  => "Sant'Angelo di Piove di Sacco",
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28083',
        'nome'  => "Sant'Elena",
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28084',
        'nome'  => "Sant'Urbano",
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28085',
        'nome'  => 'Saonara',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28086',
        'nome'  => 'Selvazzano Dentro',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28087',
        'nome'  => 'Solesino',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28088',
        'nome'  => 'Stanghella',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28089',
        'nome'  => 'Teolo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28090',
        'nome'  => 'Terrassa Padovana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Piove di Sacco',
        'frazioni' => [],
    ],
    [
        'istat' => '28091',
        'nome'  => 'Tombolo',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28092',
        'nome'  => 'Torreglia',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '28093',
        'nome'  => 'Trebaseleghe',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28094',
        'nome'  => 'Tribano',
        'provincia' => 'PD',
        'zona_bollettino' => 'Monselice',
        'frazioni' => [],
    ],
    [
        'istat' => '28095',
        'nome'  => 'Urbana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28096',
        'nome'  => 'Veggiano',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28097',
        'nome'  => 'Vescovana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28098',
        'nome'  => "Vighizzolo d'Este",
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28099',
        'nome'  => 'Vigodarzere',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28100',
        'nome'  => 'Vigonza',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28101',
        'nome'  => 'Villa del Conte',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28102',
        'nome'  => 'Villa Estense',
        'provincia' => 'PD',
        'zona_bollettino' => 'Este',
        'frazioni' => [],
    ],
    [
        'istat' => '28103',
        'nome'  => 'Villafranca Padovana',
        'provincia' => 'PD',
        'zona_bollettino' => 'Padova',
        'frazioni' => [],
    ],
    [
        'istat' => '28104',
        'nome'  => 'Villanova di Camposampiero',
        'provincia' => 'PD',
        'zona_bollettino' => 'Cittadella',
        'frazioni' => [],
    ],
    [
        'istat' => '28105',
        'nome'  => "Vo'",
        'provincia' => 'PD',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
];
