<?php

return [
    [
        'istat' => '29001',
        'nome'  => 'Adria',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29002',
        'nome'  => 'Ariano nel Polesine',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29003',
        'nome'  => "Arqua' Polesine",
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29004',
        'nome'  => 'Badia Polesine',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29005',
        'nome'  => 'Bagnolo di Po',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29006',
        'nome'  => 'Bergantino',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29007',
        'nome'  => 'Bosaro',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29008',
        'nome'  => 'Calto',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29009',
        'nome'  => 'Canaro',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29010',
        'nome'  => 'Canda',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29011',
        'nome'  => 'Castelguglielmo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29012',
        'nome'  => 'Castelmassa',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29013',
        'nome'  => 'Castelnovo Bariano',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29014',
        'nome'  => 'Ceneselli',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29015',
        'nome'  => 'Ceregnano',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29017',
        'nome'  => 'Corbola',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29018',
        'nome'  => 'Costa di Rovigo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29019',
        'nome'  => 'Crespino',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29021',
        'nome'  => 'Ficarolo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29022',
        'nome'  => 'Fiesso Umbertiano',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29023',
        'nome'  => 'Frassinelle Polesine',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29024',
        'nome'  => 'Fratta Polesine',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29025',
        'nome'  => 'Gaiba',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29026',
        'nome'  => 'Gavello',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29027',
        'nome'  => 'Giacciano con Baruchella',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29028',
        'nome'  => 'Guarda Veneta',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29029',
        'nome'  => 'Lendinara',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29030',
        'nome'  => 'Loreo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29031',
        'nome'  => 'Lusia',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29032',
        'nome'  => 'Melara',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29033',
        'nome'  => 'Occhiobello',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29034',
        'nome'  => 'Papozze',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29035',
        'nome'  => 'Pettorazza Grimani',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29036',
        'nome'  => 'Pincara',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29037',
        'nome'  => 'Polesella',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29038',
        'nome'  => 'Pontecchio Polesine',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29039',
        'nome'  => 'Porto Tolle',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29052',
        'nome'  => 'Porto Viro',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29040',
        'nome'  => 'Rosolina',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29041',
        'nome'  => 'Rovigo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Rovigo',
        'frazioni' => [],
    ],
    [
        'istat' => '29042',
        'nome'  => 'Salara',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29043',
        'nome'  => 'San Bellino',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29044',
        'nome'  => 'San Martino di Venezze',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29045',
        'nome'  => 'Stienta',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29046',
        'nome'  => 'Taglio di Po',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29047',
        'nome'  => 'Trecenta',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29048',
        'nome'  => 'Villadose',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29050',
        'nome'  => 'Villanova del Ghebbo',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
    [
        'istat' => '29051',
        'nome'  => 'Villanova Marchesana',
        'provincia' => 'RO',
        'zona_bollettino' => 'Adria',
        'frazioni' => [],
    ],
    [
        'istat' => '29049',
        'nome'  => 'Villlamarzana',
        'provincia' => 'RO',
        'zona_bollettino' => 'Badia Polesine',
        'frazioni' => [],
    ],
];
