<?php

return [
    [
        'istat' => '26001',
        'nome'  => 'Altivole',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26002',
        'nome'  => 'Arcade',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26003',
        'nome'  => 'Asolo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26004',
        'nome'  => 'Borso del Grappa',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26005',
        'nome'  => 'Breda di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26006',
        'nome'  => 'Caerano di San Marco',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26007',
        'nome'  => 'Cappella Maggiore',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26008',
        'nome'  => 'Carbonera',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26009',
        'nome'  => 'Casale sul Sile',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26010',
        'nome'  => 'Casier',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26011',
        'nome'  => 'Castelcucco',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26012',
        'nome'  => 'Castelfranco Veneto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26013',
        'nome'  => 'Castello di Godego',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26014',
        'nome'  => 'Cavaso del Tomba',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26015',
        'nome'  => 'Cessalto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26016',
        'nome'  => 'Chiarano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26017',
        'nome'  => 'Cimadolmo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26018',
        'nome'  => 'Cison di Valmarino',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26019',
        'nome'  => "Codogne'",
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26020',
        'nome'  => 'Colle Umberto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26021',
        'nome'  => 'Conegliano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26022',
        'nome'  => 'Cordignano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26023',
        'nome'  => 'Cornuda',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26025',
        'nome'  => 'Crocetta del Montello',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26026',
        'nome'  => 'Farra di Soligo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26027',
        'nome'  => 'Follina',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26028',
        'nome'  => 'Fontanelle',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26029',
        'nome'  => 'Fonte',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26030',
        'nome'  => 'Fregona',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26031',
        'nome'  => 'Gaiarine',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26032',
        'nome'  => 'Giavera del Montello',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26033',
        'nome'  => "Godega di Sant'Urbano",
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26034',
        'nome'  => 'Gorgo al Monticano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26035',
        'nome'  => 'Istrana',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26036',
        'nome'  => 'Loria',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26037',
        'nome'  => "Mansue'",
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26038',
        'nome'  => 'Mareno di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26039',
        'nome'  => 'Maser',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26040',
        'nome'  => 'Maserada sul Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26041',
        'nome'  => 'Meduna di Livenza',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26042',
        'nome'  => 'Miane',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26043',
        'nome'  => 'Mogliano Veneto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26044',
        'nome'  => 'Monastier di Treviso',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26045',
        'nome'  => 'Monfumo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26046',
        'nome'  => 'Montebelluna',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26047',
        'nome'  => 'Morgano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26048',
        'nome'  => 'Moriago della Battaglia',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26049',
        'nome'  => 'Motta di Livenza',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26050',
        'nome'  => 'Nervesa della Battaglia',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26051',
        'nome'  => 'Oderzo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26052',
        'nome'  => 'Ormelle',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26053',
        'nome'  => 'Orsago',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26055',
        'nome'  => 'Paese',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26056',
        'nome'  => 'Pederobba',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26096',
        'nome'  => 'Pieve del Grappa',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26057',
        'nome'  => 'Pieve di Soligo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26058',
        'nome'  => 'Ponte di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26059',
        'nome'  => 'Ponzano Veneto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26060',
        'nome'  => 'Portobuffole',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26061',
        'nome'  => 'Possagno',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26062',
        'nome'  => 'Povegliano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26063',
        'nome'  => 'Preganziol',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26064',
        'nome'  => 'Quinto di Treviso',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26065',
        'nome'  => 'Refrontolo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26066',
        'nome'  => 'Resana',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26067',
        'nome'  => 'Revine Lago',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26068',
        'nome'  => 'Riese Pio X',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26069',
        'nome'  => 'Roncade',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26070',
        'nome'  => 'Salgareda',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26071',
        'nome'  => 'San Biagio di Callalta',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26072',
        'nome'  => 'San Fior',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26073',
        'nome'  => 'San Pietro di Feletto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26074',
        'nome'  => 'San Polo di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26076',
        'nome'  => 'San Vendemiano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26077',
        'nome'  => 'San Zenone degli Ezzelini',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26075',
        'nome'  => 'Santa Lucia di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26078',
        'nome'  => 'Sarmede',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26079',
        'nome'  => 'Segusino',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26080',
        'nome'  => 'Sernaglia della Battaglia',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26081',
        'nome'  => 'Silea',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26082',
        'nome'  => 'Spresiano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26083',
        'nome'  => 'Susegana',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26084',
        'nome'  => 'Tarzo',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26085',
        'nome'  => 'Trevignano',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26086',
        'nome'  => 'Treviso',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26087',
        'nome'  => 'Valdobbiadene',
        'provincia' => 'TV',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '26088',
        'nome'  => 'Vazzola',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26089',
        'nome'  => 'Vedelago',
        'provincia' => 'TV',
        'zona_bollettino' => 'Castelfranco Veneto',
        'frazioni' => [],
    ],
    [
        'istat' => '26090',
        'nome'  => 'Vidor',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26091',
        'nome'  => 'Villorba',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
    [
        'istat' => '26092',
        'nome'  => 'Vittorio Veneto',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26093',
        'nome'  => 'Volpago del Montello',
        'provincia' => 'TV',
        'zona_bollettino' => 'Conegliano',
        'frazioni' => [],
    ],
    [
        'istat' => '26094',
        'nome'  => 'Zenson di Piave',
        'provincia' => 'TV',
        'zona_bollettino' => 'Mansuè',
        'frazioni' => [],
    ],
    [
        'istat' => '26095',
        'nome'  => 'Zero Branco',
        'provincia' => 'TV',
        'zona_bollettino' => 'Treviso',
        'frazioni' => [],
    ],
];
