<?php

return [
    [
        'istat' => '27001',
        'nome'  => 'Annone Veneto',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27002',
        'nome'  => 'Campagna Lupia',
        'provincia' => 'VE',
        'zona_bollettino' => 'Chioggia',
        'frazioni' => [],
    ],
    [
        'istat' => '27003',
        'nome'  => 'Campolongo Maggiore',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27004',
        'nome'  => 'Camponogara',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27005',
        'nome'  => 'Caorle',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27044',
        'nome'  => 'Cavallino-Treporti',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27006',
        'nome'  => 'Cavarzere',
        'provincia' => 'VE',
        'zona_bollettino' => 'Chioggia',
        'frazioni' => [],
    ],
    [
        'istat' => '27007',
        'nome'  => 'Ceggia',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27008',
        'nome'  => 'Chioggia',
        'provincia' => 'VE',
        'zona_bollettino' => 'Chioggia',
        'frazioni' => [],
    ],
    [
        'istat' => '27009',
        'nome'  => 'Cinto Caomaggiore',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27010',
        'nome'  => 'Cona',
        'provincia' => 'VE',
        'zona_bollettino' => 'Chioggia',
        'frazioni' => [],
    ],
    [
        'istat' => '27011',
        'nome'  => 'Concordia Sagittaria',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27012',
        'nome'  => 'Dolo',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27013',
        'nome'  => 'Eraclea',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27014',
        'nome'  => "Fiesso d'Artico",
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27015',
        'nome'  => 'Fossalta di Piave',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27016',
        'nome'  => 'Fossalta di Portogruaro',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27017',
        'nome'  => "Fosso'",
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27018',
        'nome'  => 'Gruaro',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27019',
        'nome'  => 'Jesolo',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27020',
        'nome'  => 'Marcon',
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27021',
        'nome'  => 'Martellago',
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27022',
        'nome'  => 'Meolo',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27023',
        'nome'  => 'Mira',
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27024',
        'nome'  => 'Mirano',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27025',
        'nome'  => 'Musile di Piave',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27026',
        'nome'  => 'Noale',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27027',
        'nome'  => 'Noventa di Piave',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27028',
        'nome'  => 'Pianiga',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27029',
        'nome'  => 'Portogruaro',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27030',
        'nome'  => 'Pramaggiore',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27031',
        'nome'  => "Quarto d'Altino",
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27032',
        'nome'  => 'Salzano',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27033',
        'nome'  => "San Dona' di Piave",
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27034',
        'nome'  => 'San Michele al Tagliamento',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27036',
        'nome'  => 'San Stino di Livenza',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27035',
        'nome'  => 'Santa Maria di Sala',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27037',
        'nome'  => "Scorze'",
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27038',
        'nome'  => 'Spinea',
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27039',
        'nome'  => 'Stra',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
    [
        'istat' => '27040',
        'nome'  => 'Teglio Veneto',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27041',
        'nome'  => 'Torre di Mosto',
        'provincia' => 'VE',
        'zona_bollettino' => "S. Donà di Piave",
        'frazioni' => [],
    ],
    [
        'istat' => '27042',
        'nome'  => 'VENEZIA',
        'provincia' => 'VE',
        'zona_bollettino' => 'Venezia',
        'frazioni' => [],
    ],
    [
        'istat' => '27043',
        'nome'  => 'Vigonovo',
        'provincia' => 'VE',
        'zona_bollettino' => 'Mirano',
        'frazioni' => [],
    ],
];
