<?php

return [
    [
        'istat' => '24001',
        'nome'  => 'Agugliaro',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24002',
        'nome'  => 'Albettone',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24003',
        'nome'  => 'Alonte',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24004',
        'nome'  => 'Altavilla Vicentina',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24005',
        'nome'  => 'Altissimo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24006',
        'nome'  => 'Arcugnano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24007',
        'nome'  => 'Arsiero',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24008',
        'nome'  => 'Arzignano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24009',
        'nome'  => 'Asiago',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24010',
        'nome'  => 'Asigliano Veneto',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24124',
        'nome'  => 'Barbarano Mossano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24012',
        'nome'  => 'Bassano del Grappa',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24013',
        'nome'  => 'Bolzano Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24014',
        'nome'  => 'Breganze',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24015',
        'nome'  => 'Brendola',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24016',
        'nome'  => 'Bressanvido',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24017',
        'nome'  => 'Brogliano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24018',
        'nome'  => 'Caldogno',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24019',
        'nome'  => 'Caltrano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24020',
        'nome'  => 'Calvene',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24021',
        'nome'  => 'Camisano Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24022',
        'nome'  => 'Campiglia dei Berici',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24024',
        'nome'  => "Carre'",
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24025',
        'nome'  => 'Cartigliano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24026',
        'nome'  => 'Cassola',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24027',
        'nome'  => 'Castegnero',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24028',
        'nome'  => 'Castelgomberto',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24029',
        'nome'  => 'Chiampo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24030',
        'nome'  => 'Chiuppano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24032',
        'nome'  => 'Cogollo del Cengio',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24126',
        'nome'  => 'Colceresa',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24034',
        'nome'  => 'Cornedo Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24035',
        'nome'  => 'Costabissara',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24036',
        'nome'  => 'Creazzo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24037',
        'nome'  => 'Crespadoro',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24038',
        'nome'  => 'Dueville',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24039',
        'nome'  => 'Enego',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24040',
        'nome'  => 'Fara Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24041',
        'nome'  => 'Foza',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24042',
        'nome'  => 'Gallio',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24043',
        'nome'  => 'Gambellara',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24044',
        'nome'  => 'Gambugliano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24046',
        'nome'  => 'Grisignano di Zocco',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24047',
        'nome'  => 'Grumolo delle Abbadesse',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24048',
        'nome'  => 'Isola Vicentina',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24049',
        'nome'  => 'Laghi',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24050',
        'nome'  => 'Lastebasse',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24051',
        'nome'  => 'Longare',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24052',
        'nome'  => 'Lonigo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24053',
        'nome'  => 'Lugo di Vicenza',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24127',
        'nome'  => 'Lusiana Conco',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24055',
        'nome'  => 'Malo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24056',
        'nome'  => 'Marano Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24057',
        'nome'  => 'Marostica',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24063',
        'nome'  => 'Monte di Malo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24060',
        'nome'  => 'Montebello Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24061',
        'nome'  => 'Montecchio Maggiore',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24062',
        'nome'  => 'Montecchio Precalcino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24064',
        'nome'  => 'Montegalda',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24065',
        'nome'  => 'Montegaldella',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24066',
        'nome'  => 'Monteviale',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24067',
        'nome'  => 'Monticello Conte Otto',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24068',
        'nome'  => 'Montorso Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24070',
        'nome'  => 'Mussolente',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24071',
        'nome'  => 'Nanto',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24072',
        'nome'  => 'Nogarole Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24073',
        'nome'  => 'Nove',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24074',
        'nome'  => 'Noventa Vicentina',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24075',
        'nome'  => 'Orgiano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24076',
        'nome'  => 'Pedemonte',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24077',
        'nome'  => 'Pianezze',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24078',
        'nome'  => 'Piovene Rocchette',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24079',
        'nome'  => 'Poiana Maggiore',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24080',
        'nome'  => 'Posina',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24081',
        'nome'  => 'Pove del Grappa',
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24082',
        'nome'  => 'Pozzoleone',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24083',
        'nome'  => 'Quinto Vicentino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24084',
        'nome'  => 'Recoaro Terme',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24085',
        'nome'  => 'Roana',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24086',
        'nome'  => "Romano d'Ezzelino",
        'provincia' => 'VI',
        'zona_bollettino' => 'Bassano del Grappa',
        'frazioni' => [],
    ],
    [
        'istat' => '24087',
        'nome'  => "Rosa'",
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24088',
        'nome'  => 'Rossano Veneto',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24089',
        'nome'  => 'Rotzo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24090',
        'nome'  => 'Salcedo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24094',
        'nome'  => 'San Pietro Mussolino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24096',
        'nome'  => 'San Vito di Leguzzano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24091',
        'nome'  => 'Sandrigo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24095',
        'nome'  => 'Santorso',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24097',
        'nome'  => 'Sarcedo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24098',
        'nome'  => 'Sarego',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24099',
        'nome'  => 'Schiavon',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24100',
        'nome'  => 'Schio',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24101',
        'nome'  => 'Solagna',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24102',
        'nome'  => 'Sossano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24103',
        'nome'  => 'Sovizzo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24104',
        'nome'  => 'Tezze sul Brenta',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24105',
        'nome'  => 'Thiene',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24106',
        'nome'  => 'Tonezza del Cimone',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24107',
        'nome'  => 'Torrebelvicino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24108',
        'nome'  => 'Torri di Quartesolo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24110',
        'nome'  => 'Trissino',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24123',
        'nome'  => 'Val Liona',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24125',
        'nome'  => 'Valbrenta',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24111',
        'nome'  => 'Valdagno',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24112',
        'nome'  => 'Valdastico',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24113',
        'nome'  => 'Valli del Pasubio',
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24115',
        'nome'  => "Velo d'Astico",
        'provincia' => 'VI',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '24116',
        'nome'  => 'Vicenza',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24117',
        'nome'  => 'Villaga',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24118',
        'nome'  => 'Villaverla',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24119',
        'nome'  => "Zane'",
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
    [
        'istat' => '24120',
        'nome'  => 'Zermeghedo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Vicenza',
        'frazioni' => [],
    ],
    [
        'istat' => '24121',
        'nome'  => 'Zovencedo',
        'provincia' => 'VI',
        'zona_bollettino' => 'Cinto Euganeo',
        'frazioni' => [],
    ],
    [
        'istat' => '24122',
        'nome'  => 'Zugliano',
        'provincia' => 'VI',
        'zona_bollettino' => 'Schio',
        'frazioni' => [],
    ],
];
