<?php

return [
    [
        'istat' => '23001',
        'nome'  => 'Affi',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23002',
        'nome'  => "Albaredo d'Adige",
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23003',
        'nome'  => 'Angiari',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23004',
        'nome'  => 'Arcole',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23005',
        'nome'  => 'Badia Calavena',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23006',
        'nome'  => 'Bardolino',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23007',
        'nome'  => 'Belfiore',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23008',
        'nome'  => 'Bevilacqua',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23009',
        'nome'  => 'Bonavigo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23010',
        'nome'  => "Boschi Sant'Anna",
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23011',
        'nome'  => 'Bosco Chiesanuova',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23012',
        'nome'  => 'Bovolone',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23013',
        'nome'  => 'Brentino Belluno',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23014',
        'nome'  => 'Brenzone sul Garda',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23015',
        'nome'  => 'Bussolengo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23016',
        'nome'  => 'Buttapietra',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23017',
        'nome'  => 'Caldiero',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23018',
        'nome'  => 'Caprino Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23019',
        'nome'  => 'Casaleone',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23020',
        'nome'  => 'Castagnaro',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23021',
        'nome'  => "Castel d'Azzano",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23022',
        'nome'  => 'Castelnuovo del Garda',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23023',
        'nome'  => 'Cavaion Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23024',
        'nome'  => 'Cazzano di Tramigna',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23025',
        'nome'  => 'Cerea',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23026',
        'nome'  => 'Cerro Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23027',
        'nome'  => 'Cologna Veneta',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23028',
        'nome'  => 'Colognola ai Colli',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23029',
        'nome'  => 'Concamarise',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23030',
        'nome'  => 'Costermano sul Garda',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23031',
        'nome'  => "Dolce'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23032',
        'nome'  => "Erbe'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23033',
        'nome'  => 'Erbezzo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23034',
        'nome'  => 'Ferrara di Monte Baldo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23035',
        'nome'  => 'Fumane',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23036',
        'nome'  => 'Garda',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23037',
        'nome'  => 'Gazzo Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23038',
        'nome'  => 'Grezzana',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23039',
        'nome'  => 'Illasi',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23040',
        'nome'  => 'Isola della Scala',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23041',
        'nome'  => 'Isola Rizza',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23042',
        'nome'  => 'Lavagno',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23043',
        'nome'  => 'Lazise',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23044',
        'nome'  => 'Legnago',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23045',
        'nome'  => 'Malcesine',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23046',
        'nome'  => 'Marano di Valpolicella',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23047',
        'nome'  => 'Mezzane di Sotto',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23048',
        'nome'  => 'Minerbe',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23049',
        'nome'  => 'Montecchia di Crosara',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23050',
        'nome'  => "Monteforte d'Alpone",
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23051',
        'nome'  => 'Mozzecane',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23052',
        'nome'  => 'Negrar',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23053',
        'nome'  => 'Nogara',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23054',
        'nome'  => 'Nogarole Rocca',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23055',
        'nome'  => "Oppeano",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23056',
        'nome'  => "Palu'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23057',
        'nome'  => 'Pastrengo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23058',
        'nome'  => 'Pescantina',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23059',
        'nome'  => 'Peschiera del Garda',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23060',
        'nome'  => 'Povegliano Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23061',
        'nome'  => 'Pressana',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23062',
        'nome'  => 'Rivoli Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23063',
        'nome'  => "Ronca'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23064',
        'nome'  => "Ronco all'Adige",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23065',
        'nome'  => 'Roverchiara',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23067',
        'nome'  => "Rovere' Veronese",
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23066',
        'nome'  => "Roveredo di Gua'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23068',
        'nome'  => 'Salizzole',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23069',
        'nome'  => 'San Bonifacio',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23070',
        'nome'  => 'San Giovanni Ilarione',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23071',
        'nome'  => 'San Giovanni Lupatoto',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23073',
        'nome'  => 'San Martino Buon Albergo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23074',
        'nome'  => 'San Mauro di Saline',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23075',
        'nome'  => "San Pietro di Morubio",
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23076',
        'nome'  => 'San Pietro in Cariano',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23079',
        'nome'  => 'San Zeno di Montagna',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23072',
        'nome'  => 'Sanguinetto',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23077',
        'nome'  => "Sant'Ambrogio di Valpolicella",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23078',
        'nome'  => "Sant'Anna d'Alfaedo",
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23080',
        'nome'  => 'Selva di Progno',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23081',
        'nome'  => 'Soave',
        'provincia' => 'VR',
        'zona_bollettino' => 'San Bonifacio',
        'frazioni' => [],
    ],
    [
        'istat' => '23082',
        'nome'  => 'Sommacampagna',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23083',
        'nome'  => 'Sona',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23084',
        'nome'  => "Sorga'",
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23085',
        'nome'  => 'Terrazzo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23086',
        'nome'  => 'Torri del Benaco',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23087',
        'nome'  => 'Tregnago',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23088',
        'nome'  => 'Trevenzuolo',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23089',
        'nome'  => 'Valeggio sul Mincio',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23090',
        'nome'  => 'Velo Veronese',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23091',
        'nome'  => 'Verona',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23092',
        'nome'  => 'Veronella',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23093',
        'nome'  => 'Vestenanova',
        'provincia' => 'VR',
        'zona_bollettino' => 'Comune appartenente a zona montana',
        'frazioni' => [],
    ],
    [
        'istat' => '23094',
        'nome'  => 'Vigasio',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23095',
        'nome'  => 'Villa Bartolomea',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
    [
        'istat' => '23096',
        'nome'  => 'Villafranca di Verona',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23097',
        'nome'  => 'Zevio',
        'provincia' => 'VR',
        'zona_bollettino' => 'Verona',
        'frazioni' => [],
    ],
    [
        'istat' => '23098',
        'nome'  => 'Zimella',
        'provincia' => 'VR',
        'zona_bollettino' => 'Legnago',
        'frazioni' => [],
    ],
];
