<?php

return [
    'items' => [
        // [
        //     'title' => 'Gestione Albo Organizzazioni',
        //     'desc'  => "Procedura per la gestione dell'Albo delle Organizzazioni di Volontariato di Protezione Civile",
        //     'slug'  => 'gestione-albo-organizzazioni',
        //     'icon'  => 'building-office',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Gestione Piani Comunali',
        //     'desc'  => "Procedura per l'importazione e la verifica dei piani comunali informatizzati di Protezione Civile",
        //     'slug'  => 'gestione-piani-comunali',
        //     'icon'  => 'map',
        //     'roles' => ['amministratore', 'pianificazione', 'provincie'],
        // ],
        // [
        //     'title' => 'Consultazione Albo Organizzazioni',
        //     'desc'  => "Procedura per la consultazione delle Organizzazioni di Volontariato di Protezione Civile",
        //     'slug'  => 'consultazione-albo-organizzazioni',
        //     'icon'  => 'book-open',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie', 'comuni', 'volontari'],
        // ],
        // [
        //     'title' => 'Call',
        //     'desc'  => 'Procedura per la gestione delle call',
        //     'slug'  => 'call',
        //     'icon'  => 'phone',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Attivazioni 2.0',
        //     'desc'  => 'Procedura per la gestione delle attivazioni D. Lgs 1/2018',
        //     'slug'  => 'attivazioni-2-0',
        //     'icon'  => 'bolt',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie'],
        // ],
        // [
        //     'title' => 'Gestione mezzi e attrezzature',
        //     'desc'  => 'Procedura per la gestione di mezzi ed attrezzature del sistema regionale di Protezione Civile',
        //     'slug'  => 'gestione-mezzi-attrezzature',
        //     'icon'  => 'truck',
        //     'roles' => ['amministratore', 'pianificazione', 'ufficio-volontariato', 'provincie'],
        // ],
        // [
        //     'title' => 'Schede Sintetiche Comuni',
        //     'desc'  => 'Scheda di sintesi dei principali dati comunali',
        //     'slug'  => 'schede-sintetiche-comuni',
        //     'icon'  => 'document-text',
        //     'roles' => ['amministratore', 'comuni', 'prefetture', 'provincie', 'pianificazione'],
        // ],
        // [
        //     'title' => 'Rubrica Telefonica',
        //     'desc'  => 'Consultazione della rubrica telefonica (Comuni, Province, Prefetture, Org. Volontariato)',
        //     'slug'  => 'rubrica-telefonica',
        //     'icon'  => 'book-open',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie', 'comuni'],
        // ],
        // [
        //     'title' => 'Ricerca Attivazioni',
        //     'desc'  => 'Consultazione delle attivazioni delle Organizzazioni di Volontariato',
        //     'slug'  => 'ricerca-attivazioni',
        //     'icon'  => 'magnifying-glass-circle',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie'],
        // ],
         [
             'title' => 'Segnalazioni',
             'desc'  => 'Raccolta delle informazioni in emergenza',
             'slug'  => 'segnalazioni',
             'icon'  => 'megaphone',
             'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie', 'comuni', 'volontari', 'sor-mezzi-materiali'],
         ],
        // [
        //     'title' => 'Bollo Auto',
        //     'desc'  => 'Procedura per la gestione delle esenzioni della tassa di proprieta veicoli',
        //     'slug'  => 'bollo-auto',
        //     'icon'  => 'banknotes',
        //     'roles' => ['amministratore'],
        // ],
        // [
        //     'title' => 'Rischio valanghe',
        //     'desc'  => 'Rappresentazione 3D delle aree soggette a rischio valanghe post evento Ottobre 2018',
        //     'slug'  => 'rischio-valanghe',
        //     'icon'  => 'globe-alt',
        //     'roles' => ['amministratore', 'pianificazione'],
        // ],
        // [
        //     'title' => 'Presenza Volontari',
        //     'desc'  => 'Registro degli accreditamenti dei volontari',
        //     'slug'  => 'presenza-volontari',
        //     'icon'  => 'user-group',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'volontari'],
        // ],
        // [
        //     'title' => 'Gestione squadre operative',
        //     'desc'  => 'Sistema sperimentale per la creazione e il preaccreditamento delle squadre da parte delle OdV',
        //     'slug'  => 'gestione-squadre-operative',
        //     'icon'  => 'rectangle-stack',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'volontari'],
        // ],
        // [
        //     'title' => 'Accreditamenti',
        //     'desc'  => 'Gestione degli accreditamenti delle OdV presso le Sale Operative',
        //     'slug'  => 'accreditamenti',
        //     'icon'  => 'check-badge',
        //     'roles' => ['amministratore', 'ufficio-volontariato', 'prefetture', 'provincie'],
        // ],
        // [
        //     'title' => 'Gestione OdV',
        //     'desc'  => "Gestione dei dati relativi all'Organizzazione di Volontariato",
        //     'slug'  => 'gestione-odv',
        //     'icon'  => 'shield-check',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Statistiche accreditamenti',
        //     'desc'  => "Visualizza le statistiche relative all'accreditamento dei volontari",
        //     'slug'  => 'statistiche-accreditamenti',
        //     'icon'  => 'chart-bar',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Percezione sismica',
        //     'desc'  => 'Consultazione della percezione sismica segnalata da Volontari di Protezione Civile',
        //     'slug'  => 'percezione-sismica-consultazione',
        //     'icon'  => 'presentation-chart-line',
        //     'roles' => ['amministratore', 'volontari', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Accreditamento smart',
        //     'desc'  => "Conferma arrivo e partenze squadre da parte dell'Organizzazione di Volontariato",
        //     'slug'  => 'accreditamento-smart',
        //     'icon'  => 'sparkles',
        //     'roles' => ['amministratore', 'volontari', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Gestione Emergenze',
        //     'desc'  => "Visualizzazione e raccolta di informazioni utili alla gestione dell'emergenza",
        //     'slug'  => 'gestione-emergenze',
        //     'icon'  => 'exclamation-circle',
        //     'roles' => ['amministratore', 'prefetture', 'provincie', 'comuni'],
        // ],
        // [
        //     'title' => 'Scheda Ente',
        //     'desc'  => 'Scheda anagrafica dell’Ente',
        //     'slug'  => 'scheda-ente',
        //     'icon'  => 'identification',
        //     'roles' => ['amministratore', 'comuni', 'prefetture', 'provincie'],
        // ],
        // [
        //     'title' => 'Dighe',
        //     'desc'  => 'Work in progress - FASE DI TEST',
        //     'slug'  => 'dighe',
        //     'icon'  => 'rectangle-stack',
        //     'roles' => ['amministratore', 'pianificazione'],
        // ],
        // [
        //     'title' => 'Gestione Emergenze COM',
        //     'desc'  => 'Procedura provvisoria destinata ai COM',
        //     'slug'  => 'gestione-emergenze-com',
        //     'icon'  => 'exclamation-circle',
        //     'roles' => ['amministratore', 'comuni', 'provincie'],
        // ],
        // [
        //     'title' => 'Censimento Vaccini',
        //     'desc'  => 'Statistiche censimento vaccinazioni Covid-19',
        //     'slug'  => 'censimento-vaccini',
        //     'icon'  => 'chart-pie',
        //     'roles' => ['amministratore'],
        // ],
        // [
        //     'title' => 'Gestione Accreditamenti SFR',
        //     'desc'  => 'Procedura SFR per accreditamento volontari',
        //     'slug'  => 'gestione-accreditamenti-sfr',
        //     'icon'  => 'clipboard-document-check',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Gestione Emergenze Prefetture',
        //     'desc'  => 'Procedura provvisoria destinata alle Prefetture',
        //     'slug'  => 'gestione-emergenze-prefetture',
        //     'icon'  => 'exclamation-circle',
        //     'roles' => ['amministratore', 'prefetture'],
        // ],
        // [
        //     'title' => 'Aziende a Rischio Incidente Rilevante',
        //     'desc'  => 'Consultazione dei dati relativi ad aziende classificate a rischio di incidente rilevante',
        //     'slug'  => 'aziende-a-rischio-incidente-rilevante',
        //     'icon'  => 'building-office',
        //     'roles' => ['amministratore', 'pianificazione', 'prefetture', 'provincie'],
        // ],
        // [
        //     'title' => 'Anagrafica Volontari',
        //     'desc'  => 'Ricerca ed estrazione dei volontari appartenenti a Organizzazioni di Volontariato',
        //     'slug'  => 'anagrafica-volontari',
        //     'icon'  => 'user-group',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        [
            'title' => 'Gestione formazione',
            'desc'  => 'Procedura per la gestione delle attività formative',
            'slug'  => 'gestione-formazione',
            'icon'  => 'academic-cap',
            'roles' => ['amministratore', 'ufficio-volontariato'],
        ],
        // [
        //     'title' => 'AIB sintetico',
        //     'desc'  => "Procedura per l'attivazione speditiva Incendi Boschivi",
        //     'slug'  => 'aib-sintetico',
        //     'icon'  => 'fire',
        //     'roles' => ['amministratore', 'prefetture', 'provincie', 'comuni'],
        // ],
        // [
        //     'title' => 'Gestione rimborsi',
        //     'desc'  => 'Gestione delle pratiche di rimborso ex artt. 39 e 40',
        //     'slug'  => 'gestione-rimborsi',
        //     'icon'  => 'receipt-refund',
        //     'roles' => ['amministratore'],
        // ],
        // [
        //     'title' => 'Punti di monitoraggio',
        //     'desc'  => 'Punti di monitoraggio regionale e webcam',
        //     'slug'  => 'punti-di-monitoraggio',
        //     'icon'  => 'camera',
        //     'roles' => ['amministratore', 'pianificazione'],
        // ],
        // [
        //     'title' => 'Spese ripristino OCDPC 1029/2023',
        //     'desc'  => 'Emergenza Emilia-Romagna',
        //     'slug'  => 'spese-ripristino-ocdpc-1029-2023',
        //     'icon'  => 'receipt-refund',
        //     'roles' => ['amministratore'],
        // ],
        // [
        //     'title' => 'Accreditamento VVF',
        //     'desc'  => 'Sperimentale - Accreditamento volontari in attività ricerca scomparsi a cura VVF',
        //     'slug'  => 'accreditamento-vvf',
        //     'icon'  => 'shield-check',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Statistiche',
        //     'desc'  => 'Statistiche relative a singole Organizzazioni di volontariato',
        //     'slug'  => 'statistiche',
        //     'icon'  => 'chart-bar',
        //     'roles' => ['amministratore', 'ufficio-volontariato'],
        // ],
        // [
        //     'title' => 'Spese ripristino',
        //     'desc'  => 'Segnalazione delle spese di ripristino mezzi e attrezzature',
        //     'slug'  => 'spese-ripristino',
        //     'icon'  => 'receipt-refund',
        //     'roles' => ['amministratore'],
        // ],
    ],
];
