<?php

return [
    'items' => [
        [
            'title' => 'Gestione Albo Organizzazioni',
            'desc'  => "Procedura per la gestione dell'Albo delle Organizzazioni di Volontariato di Protezione Civile",
            'slug'  => 'gestione-albo-organizzazioni',
            'icon'  => 'building-office',
        ],
        [
            'title' => 'Gestione Piani Comunali',
            'desc'  => "Procedura per l'importazione e la verifica dei piani comunali informatizzati di Protezione Civile",
            'slug'  => 'gestione-piani-comunali',
            'icon'  => 'map',
        ],
        [
            'title' => 'Consultazione Albo Organizzazioni',
            'desc'  => "Procedura per la consultazione delle Organizzazioni di Volontariato di Protezione Civile",
            'slug'  => 'consultazione-albo-organizzazioni',
            'icon'  => 'book-open',
        ],
        [
            'title' => 'Call',
            'desc'  => 'Procedura per la gestione delle call',
            'slug'  => 'call',
            'icon'  => 'phone',
        ],
        [
            'title' => 'Attivazioni 2.0',
            'desc'  => 'Procedura per la gestione delle attivazioni D. Lgs 1/2018',
            'slug'  => 'attivazioni-2-0',
            'icon'  => 'bolt',
        ],
        [
            'title' => 'Gestione mezzi e attrezzature',
            'desc'  => 'Procedura per la gestione di mezzi ed attrezzature del sistema regionale di Protezione Civile',
            'slug'  => 'gestione-mezzi-attrezzature',
            'icon'  => 'truck',
        ],
        [
            'title' => 'Manutenzione del sito',
            'desc'  => 'Procedure ed utility di servizio per la manutenzione del sito Supporto PC Veneto',
            'slug'  => 'manutenzione-sito',
            'icon'  => 'wrench',
        ],
        [
            'title' => 'Schede Sintetiche Comuni',
            'desc'  => 'Scheda di sintesi dei principali dati comunali',
            'slug'  => 'schede-sintetiche-comuni',
            'icon'  => 'document-text',
        ],
        [
            'title' => 'Rubrica Telefonica',
            'desc'  => 'Consultazione della rubrica telefonica (Comuni, Province, Prefetture, Org. Volontariato)',
            'slug'  => 'rubrica-telefonica',
            'icon'  => 'book-open',
        ],
        [
            'title' => 'Ricerca Attivazioni',
            'desc'  => 'Consultazione delle attivazioni delle Organizzazioni di Volontariato',
            'slug'  => 'ricerca-attivazioni',
            'icon'  => 'magnifying-glass-circle',
        ],
        [
            'title' => 'Segnalazioni',
            'desc'  => 'Raccolta delle informazioni in emergenza - Sperimentale',
            'slug'  => 'segnalazioni',
            'icon'  => 'megaphone',
        ],
        [
            'title' => 'Bollo Auto',
            'desc'  => 'Procedura per la gestione delle esenzioni della tassa di proprieta veicoli',
            'slug'  => 'bollo-auto',
            'icon'  => 'banknotes',
        ],
        [
            'title' => 'Rischio valanghe',
            'desc'  => 'Rappresentazione 3D delle aree soggette a rischio valanghe post evento Ottobre 2018',
            'slug'  => 'rischio-valanghe',
            'icon'  => 'globe-alt',
        ],
        [
            'title' => 'Presenza Volontari',
            'desc'  => 'Registro degli accreditamenti dei volontari',
            'slug'  => 'presenza-volontari',
            'icon'  => 'user-group',
        ],
        [
            'title' => 'Gestione squadre operative',
            'desc'  => 'Sistema sperimentale per la creazione e il preaccreditamento delle squadre da parte delle OdV',
            'slug'  => 'gestione-squadre-operative',
            'icon'  => 'rectangle-stack',
        ],
        [
            'title' => 'Accreditamenti',
            'desc'  => 'Gestione degli accreditamenti delle OdV presso le Sale Operative',
            'slug'  => 'accreditamenti',
            'icon'  => 'check-badge',
        ],
        [
            'title' => 'Gestione OdV',
            'desc'  => "Gestione dei dati relativi all'Organizzazione di Volontariato",
            'slug'  => 'gestione-odv',
            'icon'  => 'shield-check',
        ],
        [
            'title' => 'Statistiche accreditamenti',
            'desc'  => "Visualizza le statistiche relative all'accreditamento dei volontari - SPERIMENTALE!!",
            'slug'  => 'statistiche-accreditamenti',
            'icon'  => 'chart-bar',
        ],
        [
            'title' => 'Percezione sismica',
            'desc'  => 'Consultazione della percezione sismica segnalata da Volontari di Protezione Civile',
            'slug'  => 'percezione-sismica-consultazione',
            'icon'  => 'presentation-chart-line',
        ],
        [
            'title' => 'Accreditamento smart',
            'desc'  => "Conferma arrivo e partenze squadre da parte dell'Organizzazione di Volontariato",
            'slug'  => 'accreditamento-smart',
            'icon'  => 'sparkles',
        ],
        [
            'title' => 'Gestione Emergenze',
            'desc'  => "Visualizzazione e raccolta di informazioni utili alla gestione dell'emergenza",
            'slug'  => 'gestione-emergenze',
            'icon'  => 'exclamation-circle',
        ],
        [
            'title' => 'Scheda Ente',
            'desc'  => 'Scheda anagrafica dell’Ente',
            'slug'  => 'scheda-ente',
            'icon'  => 'identification',
        ],
        [
            'title' => 'Dighe',
            'desc'  => 'Work in progress - FASE DI TEST',
            'slug'  => 'dighe',
            'icon'  => 'rectangle-stack',
        ],
        [
            'title' => 'Gestione Emergenze COM',
            'desc'  => 'Procedura provvisoria destinata ai COM',
            'slug'  => 'gestione-emergenze-com',
            'icon'  => 'exclamation-circle',
        ],
        [
            'title' => 'Censimento Vaccini',
            'desc'  => 'Statistiche censimento vaccinazioni Covid-19',
            'slug'  => 'censimento-vaccini',
            'icon'  => 'chart-pie',
        ],
        [
            'title' => 'Gestione Accreditamenti SFR',
            'desc'  => 'Procedura SFR per accreditamento volontari',
            'slug'  => 'gestione-accreditamenti-sfr',
            'icon'  => 'clipboard-document-check',
        ],
        [
            'title' => 'Gestione Emergenze Prefetture',
            'desc'  => 'Procedura provvisoria destinata alle Prefetture',
            'slug'  => 'gestione-emergenze-prefetture',
            'icon'  => 'exclamation-circle',
        ],
        [
            'title' => 'Aziende a Rischio Incidente Rilevante',
            'desc'  => 'Consultazione dei dati relativi ad aziende classificate a rischio di incidente rilevante',
            'slug'  => 'aziende-a-rischio-incidente-rilevante',
            'icon'  => 'building-office',
        ],
        [
            'title' => 'Anagrafica Volontari',
            'desc'  => 'Ricerca ed estrazione dei volontari appartenenti a Organizzazioni di Volontariato',
            'slug'  => 'anagrafica-volontari',
            'icon'  => 'user-group',
        ],
        [
            'title' => 'Gestione formazione',
            'desc'  => 'Procedura per la gestione delle attività formative',
            'slug'  => 'gestione-formazione',
            'icon'  => 'academic-cap',
        ],
        [
            'title' => 'AIB sintetico',
            'desc'  => "Procedura per l'attivazione speditiva Incendi Boschivi",
            'slug'  => 'aib-sintetico',
            'icon'  => 'fire',
        ],
        [
            'title' => 'Gestione rimborsi',
            'desc'  => 'Gestione delle pratiche di rimborso ex artt. 39 e 40',
            'slug'  => 'gestione-rimborsi',
            'icon'  => 'receipt-refund',
        ],
        [
            'title' => 'Punti di monitoraggio',
            'desc'  => 'Punti di monitoraggio regionale e webcam',
            'slug'  => 'punti-di-monitoraggio',
            'icon'  => 'camera',
        ],
        [
            'title' => 'Spese ripristino OCDPC 1029/2023',
            'desc'  => 'Emergenza Emilia-Romagna',
            'slug'  => 'spese-ripristino-ocdpc-1029-2023',
            'icon'  => 'receipt-refund',
        ],
        [
            'title' => 'Accreditamento VVF',
            'desc'  => 'Sperimentale - Accreditamento volontari in attività ricerca scomparsi a cura VVF',
            'slug'  => 'accreditamento-vvf',
            'icon'  => 'shield-check',
        ],
        [
            'title' => 'Statistiche',
            'desc'  => 'Statistiche relative a singole Organizzazioni di volontariato',
            'slug'  => 'statistiche',
            'icon'  => 'chart-bar',
        ],
        [
            'title' => 'Spese ripristino',
            'desc'  => 'Segnalazione delle spese di ripristino mezzi e attrezzature',
            'slug'  => 'spese-ripristino',
            'icon'  => 'receipt-refund',
        ],
    ],
];
